[env:cardputer]
platform    = espressif32@^6.5.0
board       = m5stack-stamps3
framework   = arduino

lib_deps =
    https://github.com/m5stack/M5Cardputer.git
    bblanchon/ArduinoJson@^7.1.0
    https://github.com/Arduino-IRremote/Arduino-IRremote.git#v4.4.3
    ewpa/LibSSH-ESP32
    https://github.com/schreibfaul1/ESP32-audioI2S.git#80c80489cd466b427a7aa411cc9b9499dc4d2dc0
    https://github.com/deltabeard/Peanut-GB.git

board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

monitor_speed  = 115200
upload_speed   = 1500000

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -std=gnu++17
    -DARDUINO_LOOP_STACK_SIZE=32768

build_unflags = -std=gnu++11
